<?php

use Illuminate\Database\Seeder;

class CompetitionDistancesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('UL','ULTRA 100 Mile',null,null,100,'M',0,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('UL','ULTRA 100K',100,'K',null,null,1,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('UL','ULTRA 50 Mile',null,null,50,'M',2,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('UL','ULTRA 50K',50,'K',null,null,3,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('UL','XC Marathon',null,null,26.2,'M',4,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('UL','XC Half Marathon',null,null,13.1,'M',5,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('RD','Marathon',null,null,26.2,'M',10,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('RD','Half Marathon',null,null,13.1,'M',11,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('RD','5K Road Race',5,'K',null,null,12,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('RD','3M Road Race',null,null,3,'M',13,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','Lake 9',null,null,9.3,'M',20,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','Lake 6',null,null,6.2,'M',21,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','Lake 4',null,null,4.1,'M',22,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','Katy 3',null,null,3,'M',23,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','Katy 2',null,null,2,'M',24,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','10K',10,'K',null,null,30,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','5K',5,'K',null,null,31,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','4K',4,'K',null,null,32,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','3K',3,'K',null,null,33,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','2K',2,'K',null,null,34,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','1K',1,'K',null,null,35,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','3 Mile Competition',null,null,3,'M',34,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','2 Mile Competition',null,null,2,'M',35,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('XC','1 Mile Competition',null,null,1,'M',36,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','5000 Meters',5000,'m',null,null,40,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','3200 Meter',3200,'m',null,null,41,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','2400 Meter',2400,'m',null,null,42,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','1200 Meter',1200,'m',null,null,43,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','800 Meter',800,'m',null,null,44,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','400 Meter',800,'m',null,null,45,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','200 Meter',200,'m',null,null,46,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','100 Meter',100,'m',null,null,47,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','50 Meter',50,'m',null,null,48,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','60 Yard',null,null,60,'Y',49,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','40 Yard',null,null,40,'Y',50,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('PR','Pro Agility Drill',null,null,20,'Y',51,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','10000 Meter',10000,'m',null,null,60,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','5000 Meter',5000,'m',null,null,61,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','3200 Meter',3200,'m',null,null,62,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','3000 Meter',3000,'m',null,null,63,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','2400 Meter',2400,'m',null,null,64,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','1600 Meter',1600,'m',null,null,65,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','The Mile',null,null,1,'M',66,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','800 Meter',800,'m',null,null,67,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','The 440',null,null,440,'Y',68,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','400 Meter',400,'m',null,null,69,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','200 Meter',200,'m',null,null,70,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','100 Meter',100,'m',null,null,71,null,null)");
        DB::statement("Insert into COMPETITION_DISTANCES (ID_DISCIPLINE,DISTANCE_NAME,DISTANCE_METRIC,METRIC_UNITS,DISTANCE_IMPERIAL,IMPERIAL_UNITS,DISPLAY_ORDER,CREATED_AT,UPDATED_AT) values ('TR','50',50,'m',null,null,72,null,null)");

        DB::statement("COMMIT");
    }
}
