
CREATE TABLE "NYAL_CONFERENCES" (
    "ID"                NUMBER,
    "CONFERENCE_NAME"   VARCHAR2(50) NOT NULL ENABLE,
    "COLUMN1"           TIMESTAMP(6),
    "COLUMN2"           TIMESTAMP(6),
    CONSTRAINT "NYAL_CONFERENCES_PK" PRIMARY KEY ( "ID" ) USING INDEX enable
);

CREATE OR REPLACE EDITIONABLE TRIGGER "NYAL_CONFERENCES_ID_TRG" BEFORE
    INSERT ON nyal_conferences
    FOR EACH ROW
BEGIN
    :new.id := nyal_conferences_id_seq.nextval;
END;
/

ALTER TRIGGER "NYAL_CONFERENCES_ID_TRG" ENABLE;