<?php

// use Illuminate\Support\Facades\Schema;
// use Illuminate\Database\Schema\Blueprint;
// use Illuminate\Database\Migrations\Migration;

// class CreateTaxonomyTable extends Migration
// {
//     /**
//      * Run the migrations.
//      *
//      * @return void
//      */
//     public function up()
//     {
//         Schema::create('taxonomy', function (Blueprint $table) {
//             $table->increments('id');
//             DB::Taxonomy->'CREATE TABLE "TAXONOMY" (
//     "ID"                        NUMBER
//                                     GENERATED BY DEFAULT ON NULL AS IDENTITY  
//                                     MINVALUE 1 
//                                     MAXVALUE 9999999999999999999999999999 
//                                     INCREMENT BY 1 
//                                     START WITH 1 
//                                     CACHE 20 
//                                     NOORDER 
//                                     NOCYCLE,
//     "DATA_IDENTIFICATION_ID"    NUMBER,
//     "NAME"                      VARCHAR2(150),
//     "PARENT_NODE_ID_1"          NUMBER,
//     "PARENT_NODE_ID_2"          NUMBER,
//     "SORT_ORDER_1"              NUMBER(6,3),
//     "SORT_ORDER_2"              NUMBER(6,3),
//     "TAXONOMY_NAME_ID"          NUMBER
// )';
//             // $table->timestamps();
//         // });
//     }

//     /**
//      * Reverse the migrations.
//      *
//      * @return void
//      */
//     public function down()
//     {
//         Schema::dropIfExists('taxonomy');
//     }
// }
