
--------------------------------------------------------
--  DDL for Table EVENT_ORGANIZATIONS
--------------------------------------------------------
  CREATE TABLE "EVENT_ORGANIZATIONS" ("ID" NUMBER(10,0), "ORGANIZATION_NAME" VARCHAR2(100 CHAR), "ORGANIZATION_ABBREVIATION" VARCHAR2(10 CHAR), "ORGANIZATION_WEBSITE" VARCHAR2(150 CHAR), "CONTACT_NAME" VARCHAR2(45 CHAR), "CONTACT_PHONE" VARCHAR2(10 CHAR), "RM_STATE" CHAR(2 CHAR), "CREATED_AT" TIMESTAMP (6), "UPDATED_AT" TIMESTAMP (6)) ;

REM INSERTING into EVENT_ORGANIZATIONS
SET DEFINE OFF;
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (1,'Independent',null,null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (2,'Amateur Athletic Union (AAU)','AAU',null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (3,'USA Track & Field (USATF)','USATF',null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (4,'University Interscholastic League (UIL)','UIL',null,null,null,'TX',null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (5,'Texas Association of Private and Parochial Schools (TAPPS)','TAPPS',null,null,null,'TX',null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (6,'Dallas Running Club (DRC)',null,null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (7,'J L Long Middle School',null,null,null,'9725024700','TX',null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (8,'Luke''s Locker',null,null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (9,'McKinney ISD','MISD',null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (10,'CONNECTION: NYAL_Developer',null,null,null,null,null,null,null);

--------------------------------------------------------
--  DDL for Index UNQ_EVENT_ORGANIZATIONS_ID
--------------------------------------------------------
  CREATE UNIQUE INDEX "UNQ_EVENT_ORGANIZATIONS_ID" ON "EVENT_ORGANIZATIONS" ("ID") ;

--------------------------------------------------------
--  Constraints for Table EVENT_ORGANIZATIONS
--------------------------------------------------------
  ALTER TABLE "EVENT_ORGANIZATIONS" ADD CONSTRAINT "UNQ_EVENT_ORGANIZATIONS_ID" UNIQUE ("ID") USING INDEX  ENABLE;
  ALTER TABLE "EVENT_ORGANIZATIONS" MODIFY ("ID" NOT NULL ENABLE);
