
REM INSERTING into EVENT_ORGANIZATIONS
SET DEFINE OFF;
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (1,'Independent',null,null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (2,'Amateur Athletic Union (AAU)','AAU',null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (3,'USA Track & Field (USATF)','USATF',null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (4,'University Interscholastic League (UIL)','UIL',null,null,null,'TX',null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (5,'Texas Association of Private and Parochial Schools (TAPPS)','TAPPS',null,null,null,'TX',null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (6,'Dallas Running Club (DRC)',null,null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (7,'J L Long Middle School',null,null,null,'9725024700','TX',null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (8,'Luke''s Locker',null,null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (9,'McKinney ISD','MISD',null,null,null,null,null,null);
Insert into EVENT_ORGANIZATIONS (ID,ORGANIZATION_NAME,ORGANIZATION_ABBREVIATION,ORGANIZATION_WEBSITE,CONTACT_NAME,CONTACT_PHONE,RM_STATE,CREATED_AT,UPDATED_AT) values (10,'CONNECTION: NYAL_Developer',null,null,null,null,null,null,null);
